name: 'Bantuu Veracode Baseline'
description: 'Executa o Veracode Pipeline Scan opcionalmente integrado ao baseline do Bantuu.'
author: 'Afrika Tecnologia / JuanCunhaa'
branding:
  icon: 'shield'
  color: 'purple'

inputs:
  bantuu_api_key:
    description: 'API Key usada no header X-API-Key do Bantuu (GET baseline e POST upload).'
    required: false
  enable_sca:
    description: 'Ativa/desativa o Veracode SCA em background (true/false).'
    required: false
    default: 'false'
  veracode_sca_token:
    description: 'Token de API do Veracode SCA (usado quando enable_sca = true).'
    required: false
  enable_iac:
    description: 'Ativa/desativa o Veracode IaC Scan em background (true/false).'
    required: false
    default: 'false'
  enable_pipelinescan:
    description: 'Ativa/desativa o Veracode Pipeline Scan (true/false).'
    required: false
    default: 'true'
  enable_upload_scan:
    description: 'Ativa/desativa o Veracode Upload & Scan (true/false).'
    required: false
    default: 'false'
  enable_baseline:
    description: 'Ativa/desativa o fluxo de baseline do Bantuu (true/false).'
    required: false
    default: 'true'
  enable_auto_packager:
    description: 'Ativa/desativa o uso do Veracode Auto Packager antes do scan (true/false).'
    required: false
    default: 'false'
  veracode_api_id:
    description: 'ID da API do Veracode.'
    required: true
  veracode_api_key:
    description: 'Key da API do Veracode.'
    required: true
  veracode_sandbox:
    description: 'Define se o Upload & Scan deve usar sandbox (true) ou o app principal (false).'
    required: false
    default: 'true'
  scan_file:
    description: 'Arquivo compactado enviado ao Pipeline Scan (ex.: app.zip). Usado quando o auto packager est치 desativado.'
    required: false
  policy_fail:
    description: 'Define se o scan deve quebrar o build por policy (true/false).'
    required: false
    default: 'false'
  fail_on_severity:
    description: 'Severidades que fazem o scan falhar quando h치 baseline (ex.: "Very High, High").'
    required: false

outputs:
  has_baseline:
    description: 'true/false indicando se o Bantuu possui baseline para o reposit칩rio.'
    value: ${{ steps.check_baseline.outputs.has_baseline || 'false' }}
  pipeline_status:
    description: 'Resumo do caminho seguido: com baseline, sem baseline (com upload), apenas scan ou pipeline desativado.'
    value: ${{ steps.pipeline_status_with_baseline.outputs.pipeline_status || steps.pipeline_status_without_baseline.outputs.pipeline_status || steps.pipeline_status_without_bantuu.outputs.pipeline_status || steps.pipeline_disabled_status.outputs.pipeline_status }}
  repository_full_name:
    description: 'Reposit칩rio org/repo usado para consultar e enviar baseline ao Bantuu.'
    value: ${{ steps.resolve_repo.outputs.repository_full_name }}

runs:
  using: 'composite'
  steps:
    - name: Run Veracode SCA
      id: veracode_sca
      if: inputs.enable_sca == 'true'
      shell: bash
      env:
        SRCCLR_API_TOKEN: ${{ inputs.veracode_sca_token }}
      run: |
        set -euo pipefail

        if [ -z "${SRCCLR_API_TOKEN:-}" ]; then
          echo "Erro: veracode_sca_token nao foi fornecido." >&2
          exit 1
        fi

        echo "::group::Veracode SCA"
        set +e
        curl -sSL https://sca-downloads.veracode.com/ci.sh | bash -s -- scan --allow-dirty 2>&1 | tee veracode_sca.log
        SCA_EXIT=${PIPESTATUS[1]}
        set -e
        echo "::endgroup::"

        if [ "${SCA_EXIT}" -ne 0 ]; then
          echo "::warning::Veracode SCA retornou exit code ${SCA_EXIT} (o job continua)."
        fi

    - name: Run Veracode IaC / Secrets (directory scan)
      id: veracode_iac
      if: inputs.enable_iac == 'true'
      continue-on-error: true
      uses: veracode/container_iac_secrets_scanning@v1.0.6
      with:
        vid: ${{ inputs.veracode_api_id }}
        vkey: ${{ inputs.veracode_api_key }}
        github-token: ${{ github.token }}
        command: scan
        type: directory
        source: .
        format: table
        fail_build: 'false'
        fail_build_on_error: 'false'

    - name: Prepare scan file (auto packager)
      id: prepare_scan_file
      shell: bash
      run: |
        set -euo pipefail

        ENABLE="${{ inputs.enable_auto_packager }}"
        INPUT_SCAN_FILE="${{ inputs.scan_file }}"

        if [ "${ENABLE}" = "true" ]; then
          echo "::group::Prepare scan file (Auto Packager)"
          if [ -n "${INPUT_SCAN_FILE:-}" ] && [ -f "${INPUT_SCAN_FILE}" ]; then
            echo "Usando scan_file informado: ${INPUT_SCAN_FILE}"
            echo "scan_file=${INPUT_SCAN_FILE}" >> "$GITHUB_OUTPUT"
            echo "::endgroup::"
            exit 0
          fi

          if ! command -v veracode >/dev/null 2>&1; then
            curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          fi

          WORKSPACE="${GITHUB_WORKSPACE:-$PWD}"
          if command -v veracode >/dev/null 2>&1; then
            VERACODE_CMD="$(command -v veracode)"
          elif [ -x "${WORKSPACE}/veracode" ]; then
            VERACODE_CMD="${WORKSPACE}/veracode"
            echo "${WORKSPACE}" >> "$GITHUB_PATH"
          elif [ -x "${PWD}/veracode" ]; then
            VERACODE_CMD="${PWD}/veracode"
            echo "${PWD}" >> "$GITHUB_PATH"
          else
            echo "Erro: Veracode CLI foi instalada mas o binario 'veracode' nao foi encontrado no PATH/workspace." >&2
            exit 1
          fi

          "${VERACODE_CMD}" version || true

          "${VERACODE_CMD}" package discover . || true
          set +e
          "${VERACODE_CMD}" package 2>&1 | tee veracode_package.log
          PACKAGE_EXIT=${PIPESTATUS[0]}
          set -e

          if [ "${PACKAGE_EXIT}" -ne 0 ]; then
            echo "::warning::'veracode package' retornou exit code ${PACKAGE_EXIT}; tentando fallback."
          fi

          ZIP_FILE="$(sed -n 's/.*Package created: \\([^[:space:]]\\+\\).*/\\1/p' veracode_package.log | tail -n 1 || true)"

          if [ -z "${ZIP_FILE:-}" ]; then
            shopt -s nullglob
            zips=( veracode-artifact-*.zip )
            if [ ${#zips[@]} -eq 0 ]; then
              zips=( *.zip )
            fi
            shopt -u nullglob
            if [ ${#zips[@]} -eq 0 ]; then
              echo "::warning::Nenhum arquivo .zip gerado pela Veracode CLI (Auto Packager). Gerando app.zip via 'zip' (fallback)."

              if ! command -v zip >/dev/null 2>&1; then
                sudo apt-get update -y
                sudo apt-get install -y zip
              fi

              rm -f app.zip
              zip -rq app.zip . \
                -x ".git/*" ".github/*" \
                -x "node_modules/*" "*/node_modules/*" "*/*/node_modules/*" "*/*/*/node_modules/*" \
                -x "veracode" "veracode.exe" "veracode-cli_*" \
                -x "app.zip" \
                -x "results.json" "filtered_results.json" "baseline.json" "baseline-response.json" \
                -x "veracode_package.log" "veracode_sca.log" "veracode_iac.log"

              echo "Criado app.zip (fallback):"
              ls -lh app.zip || true
              echo "scan_file=app.zip" >> "$GITHUB_OUTPUT"
              echo "::endgroup::"
              exit 0
            fi
            ZIP_FILE="${zips[0]}"
          fi

          if [ ! -f "${ZIP_FILE}" ]; then
            echo "Erro: arquivo '${ZIP_FILE}' nao encontrado apos o Auto Packager." >&2
            exit 1
          fi

          TARGET="app.zip"

          if [ "${TARGET}" != "${ZIP_FILE}" ]; then
            cp "${ZIP_FILE}" "${TARGET}"
          fi

          echo "Criado app.zip:"
          ls -lh "${TARGET}" || true
          echo "scan_file=${TARGET}" >> "$GITHUB_OUTPUT"
          echo "::endgroup::"
        else
          if [ -z "${INPUT_SCAN_FILE}" ]; then
            echo "Erro: scan_file nao foi fornecido e enable_auto_packager esta 'false'." >&2
            exit 1
          fi

          if [ ! -f "${INPUT_SCAN_FILE}" ]; then
            echo "Erro: arquivo '${INPUT_SCAN_FILE}' nao encontrado." >&2
            exit 1
          fi

          echo "scan_file=${INPUT_SCAN_FILE}" >> "$GITHUB_OUTPUT"
        fi

    - name: Resolve repository full name
      id: resolve_repo
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        set -euo pipefail

        REPO="${GITHUB_REPOSITORY:-}"
        if [ -z "${REPO}" ]; then
          echo "Erro: github.repository nao esta definido no contexto." >&2
          exit 1
        fi

        echo "repository_full_name=${REPO}" >> "$GITHUB_OUTPUT"

    - name: Ensure jq is installed (baseline flow)
      id: ensure_jq
      if: inputs.enable_pipelinescan == 'true' && inputs.enable_baseline == 'true'
      shell: bash
      run: |
        set -euo pipefail

        if ! command -v jq >/dev/null 2>&1; then
          sudo apt-get update -y
          sudo apt-get install -y jq
        fi

    - name: Check baseline from Bantuu
      id: check_baseline
      if: inputs.enable_pipelinescan == 'true' && inputs.enable_baseline == 'true'
      shell: bash
      env:
        BANTUU_API_KEY: ${{ inputs.bantuu_api_key }}
        REPOSITORY_FULL_NAME: ${{ steps.resolve_repo.outputs.repository_full_name }}
      run: |
        set -euo pipefail

        echo "::group::Bantuu baseline (check)"
        if [ -z "${BANTUU_API_KEY:-}" ]; then
          echo "Erro: bantuu_api_key nao foi fornecida." >&2
          exit 1
        fi

        RESPONSE_FILE="baseline-response.json"
        BANTUU_BASE_URL="https://www.bantuu.io"

        HTTP_STATUS=$(curl -sS -w "%{http_code}" -o "${RESPONSE_FILE}" \
          -H "X-API-Key: ${BANTUU_API_KEY}" \
          "${BANTUU_BASE_URL}/api/veracode/baseline?repositoryFullName=${REPOSITORY_FULL_NAME}")

        if [ "${HTTP_STATUS}" -ge 400 ]; then
          echo '{}' > "${RESPONSE_FILE}"
        fi

        if [ ! -s "${RESPONSE_FILE}" ]; then
          echo '{}' > "${RESPONSE_FILE}"
        fi

        HAS_BASELINE=$(jq -r '.hasBaseline // false' "${RESPONSE_FILE}")
        if [ "${HAS_BASELINE}" != "true" ]; then
          HAS_BASELINE="false"
        fi

        echo "has_baseline=${HAS_BASELINE}" >> "$GITHUB_OUTPUT"
        echo "has_baseline=${HAS_BASELINE}"
        echo "::endgroup::"

    - name: Create local baseline file from Bantuu
      id: create_local_baseline
      if: inputs.enable_pipelinescan == 'true' && inputs.enable_baseline == 'true' && steps.check_baseline.outputs.has_baseline == 'true'
      shell: bash
      run: |
        set -euo pipefail
        jq '.results' baseline-response.json > baseline.json

    - name: Run Veracode Pipeline Scan with baseline
      id: pipeline_with_baseline
      if: inputs.enable_pipelinescan == 'true' && inputs.enable_baseline == 'true' && steps.check_baseline.outputs.has_baseline == 'true'
      continue-on-error: ${{ inputs.policy_fail != 'true' }}
      uses: veracode/Veracode-pipeline-scan-action@v1.0.20
      with:
        vid: ${{ inputs.veracode_api_id }}
        vkey: ${{ inputs.veracode_api_key }}
        file: ${{ steps.prepare_scan_file.outputs.scan_file }}
        baseline_file: 'baseline.json'
        fail_build: ${{ inputs.policy_fail }}
        fail_on_severity: ${{ inputs.fail_on_severity }}
        json_output: 'true'
        json_output_file: 'results.json'

    - name: Validate results.json (with baseline)
      id: validate_results_with_baseline
      if: inputs.enable_pipelinescan == 'true' && inputs.enable_baseline == 'true' && steps.check_baseline.outputs.has_baseline == 'true'
      shell: bash
      run: |
        set -euo pipefail
        test -f results.json

    - name: Run Veracode Pipeline Scan without baseline (Bantuu enabled)
      id: pipeline_without_baseline
      if: inputs.enable_pipelinescan == 'true' && inputs.enable_baseline == 'true' && steps.check_baseline.outputs.has_baseline == 'false'
      continue-on-error: ${{ inputs.policy_fail != 'true' }}
      uses: veracode/Veracode-pipeline-scan-action@v1.0.20
      with:
        vid: ${{ inputs.veracode_api_id }}
        vkey: ${{ inputs.veracode_api_key }}
        file: ${{ steps.prepare_scan_file.outputs.scan_file }}
        fail_build: ${{ inputs.policy_fail }}
        json_output: 'true'
        json_output_file: 'results.json'

    - name: Validate results.json (without baseline, Bantuu enabled)
      id: validate_results_without_baseline_bantuu
      if: inputs.enable_pipelinescan == 'true' && inputs.enable_baseline == 'true' && steps.check_baseline.outputs.has_baseline == 'false'
      shell: bash
      run: |
        set -euo pipefail
        test -f results.json

    - name: Upload new baseline results to Bantuu
      id: upload_results
      if: inputs.enable_pipelinescan == 'true' && inputs.enable_baseline == 'true' && steps.check_baseline.outputs.has_baseline == 'false'
      shell: bash
      env:
        BANTUU_API_KEY: ${{ inputs.bantuu_api_key }}
        REPOSITORY_FULL_NAME: ${{ steps.resolve_repo.outputs.repository_full_name }}
      run: |
        set -euo pipefail

        echo "::group::Bantuu baseline (upload)"
        if [ ! -f "results.json" ]; then
          echo "Erro: results.json nao encontrado apos o Pipeline Scan." >&2
          exit 1
        fi

        BANTUU_BASE_URL="https://www.bantuu.io"

        payload=$(jq -c --arg repo "${REPOSITORY_FULL_NAME}" \
          '. as $scan | {repositoryFullName: $repo, scanResult: $scan}' results.json)

        HTTP_STATUS=$(curl -sS -w "%{http_code}" -o /tmp/bantuu-upload-response.txt \
          -X POST "${BANTUU_BASE_URL}/api/veracode/stock-issues/upload" \
          -H "Content-Type: application/json" \
          -H "X-API-Key: ${BANTUU_API_KEY}" \
          -d "${payload}")

        if [ "${HTTP_STATUS}" -ge 400 ]; then
          echo "Erro ao enviar baseline para Bantuu. Verifique as credenciais." >&2
          cat /tmp/bantuu-upload-response.txt || true
          exit 1
        fi
        echo "::endgroup::"

    - name: Set pipeline status output (with baseline)
      id: pipeline_status_with_baseline
      if: inputs.enable_pipelinescan == 'true' && inputs.enable_baseline == 'true' && steps.check_baseline.outputs.has_baseline == 'true'
      shell: bash
      run: |
        set -euo pipefail
        echo "pipeline_status=scan_completed_with_baseline" >> "$GITHUB_OUTPUT"

    - name: Set pipeline status output (without baseline and uploaded)
      id: pipeline_status_without_baseline
      if: inputs.enable_pipelinescan == 'true' && inputs.enable_baseline == 'true' && steps.check_baseline.outputs.has_baseline == 'false'
      shell: bash
      run: |
        set -euo pipefail
        echo "pipeline_status=scan_completed_without_baseline_and_uploaded" >> "$GITHUB_OUTPUT"

    - name: Run Veracode Pipeline Scan without Bantuu
      id: pipeline_without_bantuu
      if: inputs.enable_pipelinescan == 'true' && inputs.enable_baseline != 'true'
      continue-on-error: ${{ inputs.policy_fail != 'true' }}
      uses: veracode/Veracode-pipeline-scan-action@v1.0.20
      with:
        vid: ${{ inputs.veracode_api_id }}
        vkey: ${{ inputs.veracode_api_key }}
        file: ${{ steps.prepare_scan_file.outputs.scan_file }}
        fail_build: ${{ inputs.policy_fail }}
        json_output: 'true'
        json_output_file: 'results.json'

    - name: Validate results.json (without Bantuu)
      id: validate_results_without_bantuu
      if: inputs.enable_pipelinescan == 'true' && inputs.enable_baseline != 'true'
      shell: bash
      run: |
        set -euo pipefail
        test -f results.json

    - name: Set pipeline status output (without Bantuu)
      id: pipeline_status_without_bantuu
      if: inputs.enable_pipelinescan == 'true' && inputs.enable_baseline != 'true'
      shell: bash
      run: |
        set -euo pipefail
        echo "pipeline_status=scan_completed_without_bantuu" >> "$GITHUB_OUTPUT"

    - name: Set pipeline status (pipeline scan disabled)
      id: pipeline_disabled_status
      if: inputs.enable_pipelinescan != 'true'
      shell: bash
      run: |
        set -euo pipefail

        echo "pipeline_status=pipeline_scan_disabled" >> "$GITHUB_OUTPUT"

    - name: Compute sandbox name (upload & scan)
      id: compute_upload_sandbox
      if: inputs.enable_upload_scan == 'true'
      shell: bash
      env:
        ENABLE_SANDBOX: ${{ inputs.veracode_sandbox }}
        REPOSITORY_FULL_NAME: ${{ steps.resolve_repo.outputs.repository_full_name }}
        HEAD_REF: ${{ github.head_ref }}
        REF_NAME: ${{ github.ref_name }}
      run: |
        set -euo pipefail

        branch="${HEAD_REF:-$REF_NAME}"
        if [ -z "${branch}" ]; then
          branch="unknown"
        fi

        sanitize() {
          printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9._-]+/-/g; s/^-+|-+$//g; s/-+/-/g'
        }

        branch_s="$(sanitize "${branch}")"
        repo_s="$(sanitize "${REPOSITORY_FULL_NAME}")"

        sandbox_name="${branch_s}-${repo_s}"
        sandbox_name="$(printf '%s' "${sandbox_name}" | cut -c1-80)"

        if [ "${ENABLE_SANDBOX}" != "true" ]; then
          sandbox_name=""
        fi

        echo "sandbox_name=${sandbox_name}" >> "$GITHUB_OUTPUT"

    - name: Veracode Upload & Scan (static)
      id: upload_and_scan
      if: inputs.enable_upload_scan == 'true'
      uses: veracode/veracode-uploadandscan-action@master
      with:
        appname: ${{ steps.resolve_repo.outputs.repository_full_name }}
        createprofile: true
        filepath: ${{ steps.prepare_scan_file.outputs.scan_file }}
        version: 'Scan from Bantuu Actions: ${{ github.server_url }}/${{ steps.resolve_repo.outputs.repository_full_name }} - ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}'
        vid: ${{ inputs.veracode_api_id }}
        vkey: ${{ inputs.veracode_api_key }}
        createsandbox: ${{ inputs.veracode_sandbox }}
        sandboxname: ${{ steps.compute_upload_sandbox.outputs.sandbox_name }}
        scanallnonfataltoplevelmodules: true
        includenewmodules: true
        deleteincompletescan: 2
        scantimeout: 0
