name: 'Bantuu Veracode Baseline'
description: 'Executa o Veracode Pipeline Scan opcionalmente integrado ao baseline do Bantuu.'
author: 'Afrika Tecnologia / JuanCunhaa'
branding:
  icon: 'shield'
  color: 'purple'

inputs:
  bantuu_api_key:
    description: 'API Key usada no header X-API-Key do Bantuu (GET baseline e POST upload).'
    required: false
  enable_sca:
    description: 'Ativa/desativa o Veracode SCA em background (true/false).'
    required: false
    default: 'false'
  veracode_sca_token:
    description: 'Token de API do Veracode SCA (usado quando enable_sca = true).'
    required: false
  enable_iac:
    description: 'Ativa/desativa o Veracode IaC Scan em background (true/false).'
    required: false
    default: 'false'
  enable_pipelinescan:
    description: 'Ativa/desativa o Veracode Pipeline Scan (true/false).'
    required: false
    default: 'true'
  enable_upload_scan:
    description: 'Ativa/desativa o Veracode Upload & Scan (true/false).'
    required: false
    default: 'false'
  enable_baseline:
    description: 'Ativa/desativa o fluxo de baseline do Bantuu (true/false).'
    required: false
    default: 'true'
  enable_auto_packager:
    description: 'Ativa/desativa o uso do Veracode Auto Packager antes do scan (true/false).'
    required: false
    default: 'false'
  veracode_api_id:
    description: 'ID da API do Veracode.'
    required: true
  veracode_api_key:
    description: 'Key da API do Veracode.'
    required: true
  veracode_appname:
    description: 'Nome do aplicativo no Veracode. Default: org/repo do GitHub.'
    required: false
    default: '${{ github.repository }}'
  veracode_sandbox:
    description: 'Define se o Upload & Scan deve usar sandbox (true) ou o app principal (false).'
    required: false
    default: 'true'
  scan_file:
    description: 'Arquivo compactado enviado ao Pipeline Scan (ex.: app.zip). Usado quando o auto packager est치 desativado.'
    required: false
  policy_fail:
    description: 'Define se o scan deve quebrar o build por policy (true/false).'
    required: false
    default: 'false'
  fail_on_severity:
    description: 'Severidades que fazem o scan falhar quando h치 baseline (ex.: "Very High, High").'
    required: false

outputs:
  has_baseline:
    description: 'true/false indicando se o Bantuu possui baseline para o reposit칩rio.'
    value: ${{ steps.bantuu_baseline_flow.outputs.has_baseline || 'false' }}
  pipeline_status:
    description: 'Resumo do caminho seguido: com baseline, sem baseline (com upload), apenas scan ou pipeline desativado.'
    value: ${{ steps.bantuu_baseline_flow.outputs.pipeline_status || steps.pipeline_without_bantuu.outputs.pipeline_status || steps.pipeline_disabled_status.outputs.pipeline_status }}
  repository_full_name:
    description: 'Reposit칩rio org/repo usado para consultar e enviar baseline ao Bantuu.'
    value: ${{ steps.resolve_repo.outputs.repository_full_name }}

runs:
  using: 'composite'
  steps:
    - name: Run Veracode SCA (background)
      id: veracode_sca
      if: inputs.enable_sca == 'true'
      uses: ./internal/veracode-sca
      with:
        veracode_sca_token: ${{ inputs.veracode_sca_token }}

    - name: Run Veracode IaC Scan (background)
      id: veracode_iac
      if: inputs.enable_iac == 'true'
      uses: ./internal/veracode-iac
      with:
        veracode_api_id: ${{ inputs.veracode_api_id }}
        veracode_api_key: ${{ inputs.veracode_api_key }}

    - name: Prepare scan file (auto packager)
      id: prepare_scan_file
      uses: ./internal/auto-packager
      with:
        enable_auto_packager: ${{ inputs.enable_auto_packager }}
        scan_file: ${{ inputs.scan_file }}

    - name: Resolve repository full name
      id: resolve_repo
      uses: ./internal/resolve-repo

    - name: Run Veracode Pipeline Scan with Bantuu baseline
      id: bantuu_baseline_flow
      if: inputs.enable_pipelinescan == 'true' && inputs.enable_baseline == 'true'
      uses: ./internal/bantuu-baseline-flow
      with:
        bantuu_api_key: ${{ inputs.bantuu_api_key }}
        repository_full_name: ${{ steps.resolve_repo.outputs.repository_full_name }}
        veracode_api_id: ${{ inputs.veracode_api_id }}
        veracode_api_key: ${{ inputs.veracode_api_key }}
        scan_file: ${{ steps.prepare_scan_file.outputs.scan_file }}
        policy_fail: ${{ inputs.policy_fail }}
        fail_on_severity: ${{ inputs.fail_on_severity }}

    - name: Run Veracode Pipeline Scan without Bantuu
      id: pipeline_without_bantuu
      if: inputs.enable_pipelinescan == 'true' && inputs.enable_baseline != 'true'
      uses: ./internal/pipeline-only
      with:
        veracode_api_id: ${{ inputs.veracode_api_id }}
        veracode_api_key: ${{ inputs.veracode_api_key }}
        scan_file: ${{ steps.prepare_scan_file.outputs.scan_file }}
        policy_fail: ${{ inputs.policy_fail }}

    - name: Set pipeline status (pipeline scan disabled)
      id: pipeline_disabled_status
      if: inputs.enable_pipelinescan != 'true'
      shell: bash
      run: |
        set -euo pipefail

        echo "pipeline_status=pipeline_scan_disabled" >> "$GITHUB_OUTPUT"

    - name: Veracode Upload & Scan (static)
      id: upload_and_scan
      if: inputs.enable_upload_scan == 'true'
      uses: ./internal/veracode-upload-scan
      with:
        veracode_api_id: ${{ inputs.veracode_api_id }}
        veracode_api_key: ${{ inputs.veracode_api_key }}
        veracode_appname: ${{ inputs.veracode_appname }}
        veracode_sandbox: ${{ inputs.veracode_sandbox }}
        filepath: ${{ steps.prepare_scan_file.outputs.scan_file }}

