name: Security Scan (Artefato + Bantuu baseline)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  veracode-baseline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and package application
        run: |
          # Gere o artefato para o Veracode, por exemplo app.zip
          zip -r app.zip .

      - name: Bantuu Veracode Baseline (artefato + baseline)
        id: bantuu_veracode_baseline
        uses: Afrikatec-JuanCunhaa/bantuu-baseline@v1
        with:
          bantuu_api_key: ${{ secrets.BANTUU_API_KEY }}
          veracode_api_id: ${{ secrets.VERACODE_API_ID }}
          veracode_api_key: ${{ secrets.VERACODE_API_KEY }}
          scan_file: app.zip
          enable_baseline: 'true'
          enable_auto_packager: 'false'
          policy_fail: 'false'
          # Opcional: aplicado apenas quando houver baseline
          # fail_on_severity: 'Very High, High'

      - name: Exibir outputs do Bantuu Veracode Baseline
        run: |
          echo "Has baseline? ${{ steps.bantuu_veracode_baseline.outputs.has_baseline }}"
          echo "Pipeline status: ${{ steps.bantuu_veracode_baseline.outputs.pipeline_status }}"
          echo "Repo Bantuu: ${{ steps.bantuu_veracode_baseline.outputs.repository_full_name }}"

