name: Security Scan (Auto packager + Bantuu baseline)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  veracode-baseline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bantuu Veracode Baseline (auto packager + baseline)
        id: bantuu_veracode_baseline
        uses: Afrikatec-JuanCunhaa/bantuu-baseline@v1
        with:
          bantuu_api_key: ${{ secrets.BANTUU_API_KEY }}
          veracode_api_id: ${{ secrets.VERACODE_API_ID }}
          veracode_api_key: ${{ secrets.VERACODE_API_KEY }}
          enable_auto_packager: 'true'
          enable_baseline: 'true'
          policy_fail: 'false'
          # Opcional: aplicado apenas quando houver baseline
          # fail_on_severity: 'Very High, High'

      # Outputs disponíveis no step `bantuu_veracode_baseline`:
      # - steps.bantuu_veracode_baseline.outputs.has_baseline
      # - steps.bantuu_veracode_baseline.outputs.pipeline_status
      # - steps.bantuu_veracode_baseline.outputs.repository_full_name
